about/urls.py
from django.urls import path
from . import views
# load urls.
urlpatterns = [
  
    path('contact/', views.contact, name='contact')
  
]

accounts/urls.py
from django.urls import path
from . import views
app_name = "accounts"

urlpatterns = [
    path('login/',views.login_view , name= 'login'),
    path('register/',views.register_view , name= 'register'),
    path('logout/',views.logout_view , name= 'logout'),
]

blogapp/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from post import views as post_views

# url for blog apps.
urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/',include('post.urls')),
    path('accounts/',include('accounts.urls')),
    path('about/',include('about.urls')),
    path('',post_views.home, name='home'),
]

urlpatterns = urlpatterns+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views

# urls for post.
urlpatterns = [
    path('about/', views.about, name='about'), 
    path('home/',views.home, name= 'home'),
    path('create/',views.create, name= 'create'),
    path('<slug>/', views.show, name='show'),
    path('edit/<int:pk>/', views.edit, name='edit'),  
    path('delete/<int:pk>', views.delete, name='delete'), 
    path('export', views.export, name='export'),
   
   
]

about/models.py
from django.db import models

# contact model.
class Contact(models.Model):
    name =  models.CharField(max_length=50)
    email = models.EmailField()
    message = models.TextField()
    class Meta:
        db_table = "contact"
    

accounts/models.py
from django.db import models

# Create your models here.

post/models.py
from django.db import models
from django.contrib.auth.models import User

# Create model for post.
class Post(models.Model):
    title =  models.CharField(max_length=50)
    slug = models.SlugField(unique=True)
    content = models.TextField()
    image = models.ImageField(default='default.png')
    author = models.ForeignKey(User,default=None,on_delete=models.CASCADE)
    created_on = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-created_on']
        db_table = "post"
    
    def __str__(self):
        return self.title

about/forms.py
from django import forms
from .import models

# create form for contact_us.
class ContactForm(forms.ModelForm):
    class Meta:
        model = models.Contact
        fields = "__all__"  # fields required in form.

post/forms.py
from django import forms
from .import models

# create forms for post based on this.
class PostForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['title','slug','content','image'] # fields need in form.

about/views.py
from django.shortcuts import render,redirect
from about.models import Contact
from about.forms import ContactForm  
from blogapp import settings  
from django.core.mail import send_mail  

# use for contact_us page.
def contact(request): 
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            subject = "Blog_Contact"  
            msg     = "Your message sent successfully thanks to contact_us."  
            to      = form.cleaned_data.get('email') 
            res     = send_mail(subject, msg, settings.EMAIL_HOST_USER, [to])  
            return redirect('home')
    else:
        form = ContactForm()
        return render(request, 'contact.html', {'form':form}) 

   

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout


# Use to perform login for user. 
def login_view(request):
    
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request,user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                    return redirect('home')
        else:
            return render(request, 'login.html', {'form': form})
    else:
        form = AuthenticationForm()
        return render(request,'login.html',{'form':form}) 

# Use to register user. 
def register_view(request):   
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('home')
        else:
            return render(request, "register.html", {"form": form})
    else:
        form = UserCreationForm()
        return render(request, "register.html", {"form": form})

# Use to logout user. 
def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('home')

post/views.py
import csv
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from post.models import Post
from .import forms

# Use to disply breif introduction about blog.
def about(request):
    return render(request, 'about.html') 

# Use to list all the post on home page. 
def home(request):
    posts = Post.objects.all().order_by('created_on')
    # pagination
    paginator = Paginator(posts, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request, 'home.html', {'posts': posts})
  
# Use to create new post.  
def create(request):
    if request.method == 'POST':
        form = forms.PostForm(request.POST, request.FILES)
        if form.is_valid():
            # save post in db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('home')
    else:
        form = forms.PostForm()
        return render(request, 'create.html', {'form':form}) 

# Use to show particular post.  
def show(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'show.html', {'post':post}) 

# Use to edit particular post. 
@login_required(login_url="/accounts/login/")
def edit(request, pk):
    if request.user.is_superuser:
        post = get_object_or_404(Post, pk=pk)
        if request.method == 'POST':
            form = forms.PostForm(request.POST, request.FILES, instance=post)
            if form.is_valid():
                # save edited post in db.
                post = form.save(commit=False)
                post.author = request.user
                post.save()
                return redirect('home')
        else:
            form = forms.PostForm(instance=post)
        return render(request, 'edit.html', {'form': form})
    else:
        return redirect('home')

# Use to delete particular post. 
@login_required(login_url="/accounts/login/")
def delete(request, pk):
    if request.user.is_superuser:
        post = Post.objects.get(pk=pk)
        if post.delete():
            return redirect('home')
        else:
            return render(request, 'show.html', {'post': post})
    else:
        return redirect('home')

# Use to download post.
@login_required(login_url="/accounts/login/")
def export(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="data.csv"'
    writer = csv.writer(response)
    writer.writerow(['Id', 'Title', 'Slug', 'Content', 'Created_on', 'Image', 'Author'])
    posts = Post.objects.all()
    for post in posts:
        writer.writerow([post.id, post.title, post.slug, post.content, post.created_on, post.image, post.author])
    return response

about/templates/contact.html
<!-- this is contact form. -->
{% extends  'index.html' %}
<!-- this is load django crispy_forms -->
{% load crispy_forms_tags %}
{% block content %}
<br/><div class="shadow p-3 mb-5 bg-white rounded container signup" id="boxshadow" style="width:35%">
    <form method="POST" action="{% url 'contact' %}">  
        {% csrf_token %}
        <h2 align="center">Contact_us</h2>
        {{ form|crispy }}
        <br/><button type="submit" class="btn btn-success btn-block">Send</button>
    </form>
</div>
{% endblock %}

accounts/templates/login.html
<!--Use to login in blog. -->
{% extends  'index.html' %}
{% load crispy_forms_tags %}
{% block content %}
<br/><div class="shadow p-3 mb-5 bg-white rounded container signup" id="boxshadow" style="width:30%">
    <form class="form" method="POST" action="{% url 'accounts:login' %}" >
        {% csrf_token %}
        <h2 align="center">Login</h2>
        {% if request.GET.next %}
        <input type="hidden" name="next" value="{{ request.GET.next }}">
        {% endif %}
        {{ form|crispy }}
        <br/><button type="submit" class="btn btn-success btn-block" >Log in</button>
    </form>
    <p class="text-center"><a href="{% url 'accounts:register' %}">Create an Account</a></p>
</div>


{% endblock %}

accounts/templates/register.html
<!--Use to register user in blog. -->
{% extends  'index.html' %}
<!-- Load django crispy_form. -->
{% load crispy_forms_tags %}
{% block content %}
<br/><div class = " container signup shadow p-3 mb-5 bg-white rounded" id="boxshadow" style="width:35%">
    <form class="form" method="POST" action="{% url 'accounts:register' %}">
        {% csrf_token %}
        <h2 align="center">Signup</h2>
        {{ form|crispy }}
        <input type="submit" class="btn btn-success btn-block" name="" id="" value="Signup">
    </form>
    <p class="text-center"><a href="{% url 'accounts:login' %}">Already have an Account?</a></p>
</div>

{% endblock %}

post/templates/about.html
<!--Use to disply about blog. -->
{% extends 'index.html' %}
<!-- Load django crispy_form. -->
{% load staticfiles %}  
{% block content %}
<br/>
<div class="shadow p-3 mb-5 bg-white rounded container signup" id="boxshadow">
    <h3><center>Welcome to blog</center></h3> 
    <img src="{% static 'images/blog7.jpg' %}" class="rounded-circle" alt="" width="304" height="236" style = "margin-left:400px; margin-bottom:20px; margin-top:10px;"> 
    <p>This is blog application this is providing you a facilty to you share your thoughts on it – then we 
    all link up our posts here,write something good and share with us.The very purpose of sharing our thoughts
    is to bring upon an intellectual atmosphere where people debate and discuss their ideas leading to greater spread of different ideas , 
    views and opinions/We hope you enjoy as much as we enjoy offering them to you.If you have any questions or comments, please don't hesitate to contact us.</p>
</div>
{% endblock %}

post/templates/create.html
<!--Use to create post in blog. -->
{% extends  'index.html' %}
<!-- Load django crispy_form. -->
{% load crispy_forms_tags %}
{% block content %}
<br/><div class="shadow p-3 mb-5 bg-white rounded container signup" id="boxshadow" style="width:35%">
    <form method="POST" action="{% url 'create' %}" enctype="multipart/form-data">  
        {% csrf_token %}
        <h2 align="center">New Post</h2>
        {{ form|crispy }}
        <br/><button type="submit" class="btn btn-success btn-block">Create</button>
    </form>
</div>
{% endblock %}

post/templates/edit.html
<!--Use to edit post in blog. -->
{% extends  'index.html' %}
{% load crispy_forms_tags %}
<!-- Load django crispy_form. -->
{% block content %}
<br/><div class="shadow p-3 mb-5 bg-white rounded container signup" id="boxshadow" style="width:40%">
    <form method="POST" action="{% url 'edit' pk=form.instance.pk %}" enctype="multipart/form-data">  
        {% csrf_token %}
        <h2 align="center">Edit Post</h2>
        {{ form|crispy }}
        <br/><button type="submit" class="btn btn-success btn-block">Update</button>
    </form>
</div>
{% endblock %}

post/templates/home.html
{% extends 'index.html' %}
{% load staticfiles %}  
{% block content %}
<!-- Page Features -->
<div class="container">
    <br/>	
    <div class="row text-center">
        {% for post in posts %}
        <div class="col-sm-4">
            <div class="card h-100">
                <img class="card-img-top" src="{{post.image.url}}" alt="">
                <div class="card-body">
                    <h4 class="card-title">{{post.title}}</h4>
                    <p class="card-text">{{post.content}}</p>
                </div>
                <div class="card-footer">
                    <a href= "{% url 'show' slug=post.slug %}" class="btn btn-primary">Read More..</a>	
                </div>
            </div>
        </div>
        {% endfor %}	
    </div>
    <div>
        <div class="card-body">
            <!-- pagination -->
            {% if posts.has_other_pages %}
            <ul class="pagination" style="float: right; margin-left:5px;">
                {% if posts.has_previous %}
                <li class="page-link"><a href="?page={{ posts.previous_page_number }}">Previous</a></li>
                {% else %}
                <li class="page-link page-item disabled"><span>Previous</span></li>
                {% endif %}
                {% for i in posts.paginator.page_range %}
                {% if posts.number == i %}
                <li class="page-item page-link"><span>{{ i }} <span class="sr-only active">(current)</span></span></li>
                {% else %}
                <li class="page-item page-link"><a href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% endfor %}
                {% if posts.has_next %}
                <li class="page-link"><a href="?page={{ posts.next_page_number }}">Next</a></li>
                {% else %}
                <li class="page-link page-item disabled"><span>Next</span></li>
                {% endif %}
            </ul>
            {% endif %}
            <a href="{% url 'export'%}"><button type="button" class="btn btn-primary" style="float: right; margin-left:5px;"><span class="fa fa-download"></span> Download CSV </button></a> 
            {% if user.is_authenticated %}  
            <a href="{% url 'create' %}" ><button type="button" class="btn btn-primary" style="float: right;"><span class="fa fa-plus-circle"></span> Add Post </button></a>  
            {% endif %}
        </div>
    </div>
</div>
<br/>
{% endblock %}

post/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load staticfiles %}  
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Blog</title>
        <!-- Bootstrap core CSS -->
        <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
        <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        
        <!-- Custom styles for this template -->
        <link href="{% static 'css/modern-business.css' %}" rel="stylesheet">

    </head>
    <body>
        <!-- Navigation -->
        <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand" href="index.html">BLOG</a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home' %}">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'about'%}">About</a>
                        </li>
                        <li class="nav-item">
                                <a class="nav-link" href="{% url 'contact'%}">Contact</a>
                        </li>
                        {% if user.is_authenticated %}  
                        <li>
                            <form action="{% url 'accounts:logout' %}" method="post" class="logout-link">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-default nav-link" style="margin-bottom:2px;"><span class="fa fa-sign-out"></span> Log out</button>	
                            </form>
                        </li>
                        {% else %}    
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownBlog" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Account
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownBlog">
                                <a class="dropdown-item" href="{% url 'accounts:login' %}">Login</a>
                                <a class="dropdown-item" href="{% url 'accounts:register' %}">Register</a>               
                            </div>
                        </li>
                        {% endif %}      
                    </ul>
                </div>
            </div>
        </nav>
        <header>
            <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <!-- Slide One - Set the background image for this slide in the line below -->
                    <div class="carousel-item active">
                        <img src="{% static 'images/blog2.jpg' %}" alt="">
                        <div class="carousel-caption d-none d-md-block">
                        </div>
                    </div>
                    <!-- Slide Two - Set the background image for this slide in the line below -->
                    <div class="carousel-item">
                        <img src="{% static 'images/blog4.jpg' %}" alt="">
                        <div class="carousel-caption d-none d-md-block">  
                        </div>
                    </div>
                </div>
                <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
                </a>
                <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
                </a>
            </div>
        </header>
        {% block content %}
        {% endblock %}
        <!-- Footer -->
        <footer class="py-3 bg-dark">
            <div class="container">
                <p class="m-0 text-center text-white">Copyright &copy; Blog 2019</p>
            </div>
            <!-- /.container -->
        </footer>
        <!-- Bootstrap core JavaScript -->
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    </body>
</html>

post/templates/show.html
<!--Use to show postdetail in blog. -->
{% extends  'index.html' %}
<!-- Load django crispy_form. -->
{% include 'delete.html' %}
{% block content %}
<br/>
<div class="shadow p-3 mb-5 bg-white rounded container signup" id="boxshadow" style="width:50%">
    <h2 align="center">{{post.title}}</h2>
    <br>
    <div class="image">
        <img src="{{ post.image.url }}"  class="rounded" style="height:300px;width:450; margin-left:90px;" />
    </div>
    <br>
    <p style="text-align: justify;text-justify: inter-word;padding:20px;">{{post.content}}</p>
   
    {% if user.is_superuser %}
        <a href="{% url 'edit' pk=post.pk %}" ><button type="button" class="btn btn-primary" style="margin-left:250px;"><span class="fa fa-pencil"></span> Edit </button></a>   
        <a href="{% url 'delete' pk=post.pk %}" onclick="return confirm('Are you sure you want to delete this?')"><button type="button" class="btn btn-danger "><i class="fa fa-trash-o"></i> Delete</button></a>
    {% endif %}
</div>
{% endblock %}